"""Add num_samples and std_deviation to PlayerMetricValue

Revision ID: 7703a960c999
Revises: 
Create Date: 2025-12-01 23:15:35.769083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7703a960c999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_metric_value', sa.Column('average_value', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('player_metric_value', sa.Column('num_samples', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('player_metric_value', sa.Column('std_deviation', sa.Numeric(precision=14, scale=4), nullable=True))
    op.drop_column('player_metric_value', 'reference_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_metric_value', sa.Column('reference_value', sa.NUMERIC(precision=14, scale=4), nullable=True))
    op.drop_column('player_metric_value', 'std_deviation')
    op.drop_column('player_metric_value', 'num_samples')
    op.drop_column('player_metric_value', 'average_value')
    # ### end Alembic commands ###
